---
# tasks file for laptop
- name: Update all packages to their latest version
  ansible.builtin.apt:
    name: "*"
    state: latest
  become: true
  when: ansible_os_family == "Debian"
  tags:
    - ubuntu
    - packages

- name: Install Packages
  become: true
  ansible.builtin.apt:
    name: gnupg
    state: present

- name: Add an Apt signing key, Microsoft
  ansible.builtin.apt_key:
    url: https://packages.microsoft.com/keys/microsoft.asc
    state: present

- name: Add an Apt signing key, Dbeaver
  ansible.builtin.apt_key:
    url: https://dbeaver.io/debs/dbeaver.gpg.key
    state: present

- name: Add microsoft repository into sources list
  become: true
  ansible.builtin.apt_repository:
    repo: deb https://packages.microsoft.com/repos/vscode stable main
    state: present

- name: Add Dbeaber repository into sources list
  become: true
  ansible.builtin.apt_repository:
    repo: deb https://dbeaver.io/debs/dbeaver-ce /
    state: present

  
- name: Update all packages to their latest version
  become: true
  ansible.builtin.apt:
    name: "*"
    state: latest

- name: Install nvm
  become: true
  ansible.builtin.shell: >
    curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.2/install.sh | bash
  args:
    creates: "{{ ansible_env.HOME }}/.nvm/nvm.sh"

- name: Install Aditional Packages
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
  become: true
  loop:
    - "{{ install_packages }}" 
  when: ansible_os_family == "Debian"
  tags:
    - ubuntu
    - packages
