---
# tasks file for laptop
- name: Update all packages to their latest version
  ansible.builtin.apt:
    name: "*"
    state: latest
  become: true
  when: ansible_os_family == "Debian"
  tags:
    - ubuntu
    - packages

- name: Install Packages Pre-Requierements
  become: true
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
  loop:
    - "{{ prerequierements_packages }}"
  when: ansible_os_family == "Debian"
  tags:
    - ubuntu
    - packages

- name: Update all packages to their latest version
  become: true
  ansible.builtin.apt:
    name: "*"
    state: latest

- name: Install nvm
  become: true
  ansible.builtin.shell: >
    curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.2/install.sh | bash
  args:
    creates: "{{ ansible_env.HOME }}/.nvm/nvm.sh"

- name: Install Aditional Packages
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
  become: true
  loop:
    - "{{ install_packages }}" 
  when: ansible_os_family == "Debian"
  tags:
    - ubuntu
    - packages

- name: Install Docker Packages
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
  become: true
  loop:
    - "{{ docker_packages }}" 
  when: ansible_os_family == "Debian"
  tags:
    - docker
    - packages

- name: Install packages from other sources
  community.general.snap:
    name: "{{ item }}"
    state: present
    classic: true
  become: true
  loop:
    - "{{ install_snap_packages }}" 
  when: ansible_os_family == "Debian"
  tags:
    - docker
    - packages
