---
# tasks file for laptop
- name: Update Software
  dnf:
    name: "*"
    state: latest
  become: true
  when: ansible_distribution == "Fedora"
  tags:
    - fedora
    - packages

- name: Install Aditional Packages
  dnf:
    name: "{{ item }}"
    state: present
  become: true
  with_items:
    - vim
    - wget
    - tmux
    - powerline
    - powerline-fonts
    - tmux-powerline
    - vim-powerline
    - python-pip
    - python2-devel
    - python3-devel
    - libselinux-python
    - kernel-devel
    - kernel-headers
    - dkms
    - gcc
    - make
    - bzip2
    - perl  
    - dnf-plugins-core
    - python3-dnf-plugins-core.noarch
    - hunspell-es-*
    - remmina
  when: ansible_distribution == "Fedora"
  tags:
    - fedora
    - packages

- name: Active COPER YADM Repo
  command: dnf -y copr enable thelocehiliosan/yadm
  become: true
  tags:
    - fedora
    - packages

- name: Install YADM
  dnf:
    name: yadm
    state: latest
  become: true
  tags:
    - fedora
    - packages

- name: Copy Google Chrome Repo
  copy: 
    src: files/google-chrome.repo
    dest: /etc/yum.repos.d/
  become: true

- name: install the latest version of Google Chrome
  dnf:
    name: google-chrome-stable
    enablerepo: google-chrome
    state: present
  become: true

- name: Enable Flathub repository
  become: true
  command: flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
  ignore_errors: true
  tags:
    - fedora
    - packages

- name: Install Flathub apps
  become: true
  command: flatpak install --assumeyes flathub {{ item }}
  with_items:
    - com.spotify.Client
    - com.visualstudio.code
    - org.gnome.Fractal
    - com.dropbox.Client
    - com.skype.Client
  ignore_errors: true
  tags:
    - fedora
    - packages

- name: Configure Fedora
  command: yadm clone https://github.com/Wolfant/Dotfiles
  tags:
    - fedora
    - configure
  ignore_errors: true

- name: Install Docker
  dnf:
    name: docker
    state: latest
  become: true
  tags:
    - fedora
    - docker

- name: Active Docker
  service:
    name: docker
    state: started
    enabled: true
  become: true

- name: Pip Software
  pip:
    name: molecule
  become: true
  ignore_errors: true
